#!/usr/bin/env python3
"""Capture HTTP flows generated by an Android app after a user-supplied intent.

This is a generic capture-and-filter tool. It never creates, signs, mutates, or
replays an HTTP request: the selected Android package makes its own requests
after receiving the intent. Request filters only select which app-generated
flows are exported.

Examples:
  python deeplink_capture.py --pkg com.example.app --uri https://example.test/item/42
  python deeplink_capture.py --pkg com.example.app --uri myapp://open/42 \
      --method POST --request-body-file body.json --host api.example.test
  python deeplink_capture.py --pkg com.example.app --uri myapp://open \
      --extra source=share --extra mode=preview --path /v1/items

Prerequisites:
  - adb is connected to the intended Android device.
  - mitmdump is on PATH, or supplied with --mitmdump.
  - The mitmproxy CA is trusted by the selected app/device for HTTPS capture.

The raw mitm file and exported JSON can contain credentials and payloads. Store
them only in an ignored/private capture directory.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
from pathlib import Path
import shutil
import socket
import subprocess
import sys
import tempfile
import time
from typing import Any
from urllib.parse import urlsplit


ADDON_CONFIG_ENV = "GENERIC_DEEPLINK_CONFIG_PATH"
ADDON_SIGNAL_ENV = "GENERIC_DEEPLINK_SIGNAL_PATH"
ATOMIC_REPLACE_ATTEMPTS = 10


def message_bytes(message: Any) -> bytes:
    """Return the exact body bytes available from mitmproxy."""
    if not message:
        return b""
    raw_content = getattr(message, "raw_content", None)
    if raw_content is not None:
        return raw_content
    try:
        return getattr(message, "content", b"") or b""
    except Exception:
        return b""


def text_or_binary(message: Any) -> str:
    """Return readable mitmproxy content without application decryption."""
    content = message_bytes(message)
    if not content:
        return ""
    try:
        return message.get_text(strict=False)
    except Exception:
        return f"<{len(content)} bytes binary>"


def flow_matches_config(flow: Any, config: dict[str, Any], *, require_response: bool) -> bool:
    """Apply only generic request/response filters from a JSON-safe config."""
    request = flow.request
    response = flow.response
    if require_response and response is None:
        return False

    not_before = config.get("not_before")
    request_started = getattr(request, "timestamp_start", None)
    if not_before is not None and (request_started is None or request_started < not_before):
        return False
    if config.get("host") and request.host != config["host"]:
        return False
    if config.get("method") and request.method.upper() != config["method"].upper():
        return False
    if config.get("url") and request.pretty_url != config["url"]:
        return False

    request_path = urlsplit(request.pretty_url).path
    if config.get("path") and request_path != config["path"]:
        return False
    if config.get("path_contains") and config["path_contains"] not in request.path:
        return False
    if config.get("expected_body") is not None:
        if text_or_binary(request) != config["expected_body"]:
            return False
    if config.get("request_body_sha256"):
        digest = hashlib.sha256(message_bytes(request)).hexdigest()
        if digest.lower() != config["request_body_sha256"].lower():
            return False
    if config.get("response_status") is not None:
        if response is None or response.status_code != config["response_status"]:
            return False
    return True


def atomic_write_json(path: Path, payload: Any, *, compact: bool = False) -> None:
    """Atomically write JSON with retries for brief Windows file-lock races."""
    path.parent.mkdir(parents=True, exist_ok=True)
    temp_path = path.with_name(f".{path.name}.{os.getpid()}.tmp")
    try:
        if compact:
            text = json.dumps(payload, ensure_ascii=False)
        else:
            text = json.dumps(payload, indent=2, ensure_ascii=False) + "\n"
        temp_path.write_text(text, encoding="utf-8")
        for attempt in range(ATOMIC_REPLACE_ATTEMPTS):
            try:
                os.replace(temp_path, path)
                return
            except PermissionError:
                if attempt == ATOMIC_REPLACE_ATTEMPTS - 1:
                    raise
                time.sleep(0.1 * (attempt + 1))
    finally:
        if temp_path.exists():
            temp_path.unlink()


def response(flow: Any) -> None:
    """mitmproxy addon hook: signal the first matching completed response."""
    config_value = os.environ.get(ADDON_CONFIG_ENV)
    signal_value = os.environ.get(ADDON_SIGNAL_ENV)
    if not config_value or not signal_value:
        return

    config_path = Path(config_value)
    signal_path = Path(signal_value)
    if signal_path.exists() or not config_path.exists():
        return
    try:
        config = json.loads(config_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return
    if not flow_matches_config(flow, config, require_response=True):
        return

    event = {
        "flow_id": str(flow.id),
        "method": flow.request.method,
        "url": flow.request.pretty_url,
        "status": flow.response.status_code,
        "request_started": getattr(flow.request, "timestamp_start", None),
        "response_ended": getattr(flow.response, "timestamp_end", None),
    }
    atomic_write_json(signal_path, event, compact=True)


def parse_extra(value: str) -> tuple[str, str]:
    key, separator, item = value.partition("=")
    if not separator or not key:
        raise argparse.ArgumentTypeError("intent extras must use KEY=VALUE")
    return key, item


def read_request_body(args: argparse.Namespace) -> str | None:
    if args.request_body is not None:
        return args.request_body
    if args.request_body_file is not None:
        try:
            return Path(args.request_body_file).read_text(encoding="utf-8")
        except OSError as exc:
            raise SystemExit(f"cannot read --request-body-file: {exc}") from exc
    return None


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Trigger a user-supplied Android intent and save matching app-generated HTTP flows."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("--pkg", required=True, help="Android package to receive the intent")
    parser.add_argument("--uri", required=True, help="intent data URI, for example myapp://open/42")
    parser.add_argument("--action", default="android.intent.action.VIEW", help="Android intent action")
    parser.add_argument(
        "--extra", action="append", type=parse_extra, default=[], metavar="KEY=VALUE",
        help="string intent extra; repeat for multiple extras",
    )
    parser.add_argument("--method", help="only export flows with this HTTP method")
    request_body = parser.add_mutually_exclusive_group()
    request_body.add_argument(
        "--request-body", help="match the decoded request body exactly",
    )
    request_body.add_argument(
        "--request-body-file", help="read the exact expected request body from a UTF-8 file",
    )
    request_body.add_argument(
        "--request-body-sha256", help="match the SHA-256 of the exact request body bytes",
    )
    parser.add_argument("--host", help="only export flows whose request host exactly matches")
    parser.add_argument("--url", help="only export a flow whose complete request URL exactly matches")
    parser.add_argument("--path", help="only export flows whose URL path exactly matches")
    parser.add_argument("--path-contains", help="only export flows whose request path contains text")
    parser.add_argument(
        "--response-status", type=int, help="only export responses with this HTTP status",
    )
    parser.add_argument(
        "--wait", type=float, default=15,
        help=(
            "maximum seconds to wait for a filtered response; with no filters, "
            "capture for this full duration (default: 15)"
        ),
    )
    parser.add_argument(
        "--settle", type=float, default=0,
        help="continue capturing this many seconds after the first match (default: 0)",
    )
    parser.add_argument("--port", type=int, default=8080, help="local mitmdump port (default: 8080)")
    parser.add_argument(
        "--serial", help="ADB serial; omitted only when exactly one usable device is connected",
    )
    parser.add_argument("--adb", default="adb", help="ADB executable (default: adb on PATH)")
    parser.add_argument(
        "--mitmdump", default="mitmdump", help="mitmdump executable (default: on PATH)",
    )
    parser.add_argument("--cap", default="captures/intent_capture.mitm", help="raw mitmproxy output")
    parser.add_argument("--out", default="captures/intent_capture.json", help="matching flows JSON")
    parser.add_argument("--no-force-stop", action="store_true", help="do not stop the package")
    parser.add_argument(
        "--no-adb-proxy", action="store_true",
        help="do not change adb reverse or the Android global proxy",
    )
    parser.add_argument(
        "--leave-proxy", action="store_true",
        help="leave this tool's Android proxy and reverse mapping configured",
    )
    parser.add_argument(
        "--require-match", action="store_true",
        help="exit nonzero when no matching response is captured",
    )
    return parser.parse_args()


def executable_exists(executable: str) -> bool:
    return bool(shutil.which(executable) or Path(executable).exists())


def run(
    command: list[str],
    *,
    check: bool = True,
    timeout: float = 30,
) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        command,
        check=check,
        capture_output=True,
        text=True,
        timeout=timeout,
    )


def connected_devices(adb: str) -> list[str]:
    result = run([adb, "devices"])
    devices: list[str] = []
    for line in result.stdout.splitlines()[1:]:
        fields = line.split()
        if len(fields) >= 2 and fields[1] == "device":
            devices.append(fields[0])
    return devices


def resolve_serial(adb: str, serial: str | None) -> str:
    devices = connected_devices(adb)
    if serial:
        if serial not in devices:
            available = ", ".join(devices) or "none"
            raise ValueError(f"ADB serial {serial!r} is not usable; connected devices: {available}")
        return serial
    if len(devices) == 1:
        return devices[0]
    if not devices:
        raise ValueError("no usable ADB device is connected")
    raise ValueError(
        "multiple ADB devices are connected; pass --serial with one of: "
        + ", ".join(devices)
    )


def adb_prefix(adb: str, serial: str) -> list[str]:
    return [adb, "-s", serial]


def read_proxy(adb: list[str]) -> str:
    value = run(adb + ["shell", "settings", "get", "global", "http_proxy"]).stdout.strip()
    return value if value and value.lower() != "null" else ":0"


def set_proxy(adb: list[str], value: str) -> None:
    run(adb + ["shell", "settings", "put", "global", "http_proxy", value])


def reverse_mappings(adb: list[str]) -> dict[str, str]:
    result = run(adb + ["reverse", "--list"])
    mappings: dict[str, str] = {}
    for line in result.stdout.splitlines():
        fields = line.split()
        if len(fields) >= 2:
            remote, local = fields[-2:]
            mappings[remote] = local
    return mappings


def restore_proxy_if_owned(adb: list[str], our_proxy: str, previous_proxy: str) -> None:
    current_proxy = read_proxy(adb)
    if current_proxy != our_proxy:
        print(
            f"[!] Android proxy changed externally to {current_proxy!r}; not overwriting it",
            file=sys.stderr,
        )
        return
    set_proxy(adb, previous_proxy)
    print(f"[*] restored Android proxy to {previous_proxy!r}")


def port_is_open(port: int) -> bool:
    try:
        with socket.create_connection(("127.0.0.1", port), timeout=0.2):
            return True
    except OSError:
        return False


def wait_for_mitmproxy(mitm: subprocess.Popen[bytes], port: int, timeout: float = 30) -> None:
    deadline = time.monotonic() + timeout
    while mitm.poll() is None:
        if port_is_open(port):
            return
        if time.monotonic() >= deadline:
            mitm.kill()
            mitm.wait()
            raise RuntimeError(f"mitmdump did not bind port {port} within {timeout:g}s")
        time.sleep(0.1)
    raise RuntimeError("mitmdump exited before it started listening")


def wait_for_match(
    mitm: subprocess.Popen[bytes],
    signal_path: Path,
    timeout: float,
) -> bool:
    deadline = time.monotonic() + timeout
    while True:
        if signal_path.exists():
            return True
        if mitm.poll() is not None:
            raise RuntimeError("mitmdump exited while waiting for a matching response")
        if time.monotonic() >= deadline:
            return False
        time.sleep(0.1)


def wait_for_duration(mitm: subprocess.Popen[bytes], duration: float) -> None:
    """Collect traffic for a fixed duration when no completion filter exists."""
    deadline = time.monotonic() + duration
    while time.monotonic() < deadline:
        if mitm.poll() is not None:
            raise RuntimeError("mitmdump exited while collecting app-generated traffic")
        time.sleep(min(0.1, max(0, deadline - time.monotonic())))


def serialise(flow: Any) -> dict[str, Any]:
    request, response_message = flow.request, flow.response
    return {
        "method": request.method,
        "url": request.pretty_url,
        "req_headers": dict(request.headers),
        "req_body": text_or_binary(request),
        "req_body_bytes": len(message_bytes(request)),
        "status": response_message.status_code if response_message else None,
        "resp_headers": dict(response_message.headers) if response_message else {},
        "resp_body": text_or_binary(response_message),
        "resp_body_bytes": len(message_bytes(response_message)),
        "request_started": getattr(request, "timestamp_start", None),
        "response_ended": getattr(response_message, "timestamp_end", None),
    }


def build_match_config(
    args: argparse.Namespace,
    expected_body: str | None,
    not_before: float,
) -> dict[str, Any]:
    return {
        "not_before": not_before,
        "host": args.host,
        "method": args.method,
        "url": args.url,
        "path": args.path,
        "path_contains": args.path_contains,
        "expected_body": expected_body,
        "request_body_sha256": args.request_body_sha256,
        "response_status": args.response_status,
    }


def has_completion_filter(args: argparse.Namespace, expected_body: str | None) -> bool:
    """Return whether a response can be selected unambiguously for early exit."""
    return any(
        value is not None
        for value in (
            args.host,
            args.method,
            args.url,
            args.path,
            args.path_contains,
            expected_body,
            args.request_body_sha256,
            args.response_status,
        )
    )


def validate_args(args: argparse.Namespace) -> None:
    if args.wait < 0:
        raise SystemExit("--wait must be zero or greater")
    if args.settle < 0:
        raise SystemExit("--settle must be zero or greater")
    if not 1 <= args.port <= 65535:
        raise SystemExit("--port must be between 1 and 65535")
    if args.response_status is not None and not 100 <= args.response_status <= 599:
        raise SystemExit("--response-status must be between 100 and 599")
    if args.request_body_sha256:
        digest = args.request_body_sha256.lower()
        if len(digest) != 64:
            raise SystemExit("--request-body-sha256 must be a 64-character hexadecimal digest")
        try:
            bytes.fromhex(digest)
        except ValueError as exc:
            raise SystemExit("--request-body-sha256 must be hexadecimal") from exc
    if args.no_adb_proxy and args.leave_proxy:
        raise SystemExit("--leave-proxy cannot be combined with --no-adb-proxy")
    if not executable_exists(args.adb):
        raise SystemExit(f"adb executable was not found: {args.adb!r}")
    if not executable_exists(args.mitmdump):
        raise SystemExit(f"mitmdump executable was not found: {args.mitmdump!r}")


def stop_process(process: subprocess.Popen[bytes] | None) -> None:
    if process is None or process.poll() is not None:
        return
    process.terminate()
    try:
        process.wait(timeout=10)
    except subprocess.TimeoutExpired:
        process.kill()
        process.wait()


def main() -> int:
    args = parse_args()
    validate_args(args)
    expected_body = read_request_body(args)
    completion_filter = has_completion_filter(args, expected_body)

    try:
        serial = resolve_serial(args.adb, args.serial)
    except (FileNotFoundError, subprocess.CalledProcessError, ValueError) as exc:
        raise SystemExit(f"ADB device selection failed: {exc}") from exc
    adb = adb_prefix(args.adb, serial)

    cap_path = Path(args.cap)
    out_path = Path(args.out)
    cap_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    if cap_path.resolve() == out_path.resolve():
        raise SystemExit("--cap and --out must name different files")
    if port_is_open(args.port):
        raise SystemExit(f"local port {args.port} is already in use")
    if cap_path.exists():
        cap_path.unlink()

    mitm: subprocess.Popen[bytes] | None = None
    matched = False
    launch_time = 0.0
    previous_proxy = ":0"
    previous_reverse: str | None = None
    reverse_changed = False
    proxy_configured = False
    our_proxy = f"127.0.0.1:{args.port}"
    reverse_remote = f"tcp:{args.port}"
    reverse_local = f"tcp:{args.port}"

    with tempfile.TemporaryDirectory(prefix="generic-deeplink-capture-") as temp_dir:
        config_path = Path(temp_dir) / "match-config.json"
        signal_path = Path(temp_dir) / "match-response.json"
        mitm_environment = os.environ.copy()
        mitm_environment[ADDON_CONFIG_ENV] = str(config_path)
        mitm_environment[ADDON_SIGNAL_ENV] = str(signal_path)

        command = [
            args.mitmdump,
            "--listen-port", str(args.port),
            "-q",
            "--set", "block_global=false",
            "-w", str(cap_path),
            "-s", str(Path(__file__).resolve()),
        ]
        print(f"[*] starting mitmdump on :{args.port} -> {cap_path}")
        mitm = subprocess.Popen(
            command,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            env=mitm_environment,
        )
        wait_for_mitmproxy(mitm, args.port)

        try:
            if not args.no_adb_proxy:
                previous_proxy = read_proxy(adb)
                mappings = reverse_mappings(adb)
                previous_reverse = mappings.get(reverse_remote)
                if previous_reverse != reverse_local:
                    run(adb + ["reverse", reverse_remote, reverse_local])
                    reverse_changed = True
                set_proxy(adb, our_proxy)
                proxy_configured = True
                print(
                    f"[*] Android proxy set to {our_proxy!r}; "
                    f"previous value was {previous_proxy!r}"
                )

            if not args.no_force_stop:
                run(adb + ["shell", "am", "force-stop", args.pkg])

            launch_time = time.time()
            match_config = build_match_config(args, expected_body, launch_time)
            if completion_filter:
                atomic_write_json(config_path, match_config, compact=True)

            intent = adb + ["shell", "am", "start", "-a", args.action, "-d", args.uri]
            for key, value in args.extra:
                intent.extend(["--es", key, value])
            intent.append(args.pkg)
            print(f"[*] launching {args.pkg}: {args.action} {args.uri}")
            run(intent)

            if completion_filter:
                print(f"[*] waiting up to {args.wait:g}s for the first matching response")
                matched = wait_for_match(mitm, signal_path, args.wait)
                if matched:
                    print("[+] matching app-generated response observed")
                    if args.settle:
                        print(f"[*] collecting an additional {args.settle:g}s of traffic")
                        wait_for_duration(mitm, args.settle)
                else:
                    print("[i] no matching response arrived before the deadline")
            else:
                print(
                    f"[*] no completion filter supplied; collecting traffic for {args.wait:g}s"
                )
                wait_for_duration(mitm, args.wait)
        finally:
            if not args.no_adb_proxy and not args.leave_proxy:
                try:
                    if proxy_configured:
                        restore_proxy_if_owned(adb, our_proxy, previous_proxy)
                    if reverse_changed:
                        if previous_reverse is None:
                            run(adb + ["reverse", "--remove", reverse_remote], check=False)
                            print(f"[*] removed adb reverse mapping {reverse_remote}")
                        else:
                            run(adb + ["reverse", reverse_remote, previous_reverse])
                            print(
                                f"[*] restored adb reverse {reverse_remote} -> "
                                f"{previous_reverse}"
                            )
                except (
                    FileNotFoundError,
                    subprocess.CalledProcessError,
                    subprocess.TimeoutExpired,
                ) as exc:
                    print(f"[!] could not restore Android proxy/reverse state: {exc}", file=sys.stderr)
            elif not args.no_adb_proxy and args.leave_proxy:
                print("[*] leaving Android proxy and adb reverse mapping configured")
            stop_process(mitm)

    if not cap_path.exists():
        raise SystemExit("mitmdump did not write a capture file")

    try:
        from mitmproxy import http
        from mitmproxy.io import FlowReader
    except ImportError as exc:
        raise SystemExit("mitmproxy is required to read the capture: pip install mitmproxy") from exc

    match_config = build_match_config(args, expected_body, launch_time)
    data: list[dict[str, Any]] = []
    with cap_path.open("rb") as handle:
        for flow in FlowReader(handle).stream():
            if isinstance(flow, http.HTTPFlow) and flow_matches_config(
                flow, match_config, require_response=False
            ):
                data.append(serialise(flow))

    atomic_write_json(out_path, data)
    print(f"[+] exported {len(data)} matching HTTP flow(s) -> {out_path}")
    if not data:
        print(
            "[i] No flow matched. Check the URI/package, deadline, CA trust, and filters."
        )
    if args.require_match and (not data or (completion_filter and not matched)):
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
